# Site settings
title: New Directions
header-img: img/home-bg.jpg
email: c.s.meyns@gmail.com
description: "New Directions in the Study of the Mind Project."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: studyofthemind
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
